name: tamagotchi_duck
description: A Flutter desktop widget tamagotchi duck game with AI integration
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # Game engine for animations / Engine de jogo para animações
  flame: ^1.30.0
  # Window management for borderless widget / Gerenciamento de janela para widget sem bordas
  window_manager: ^0.5.0
  bitsdojo_window: ^0.1.6
  # Data persistence / Persistência de dados
  shared_preferences: ^2.2.2
  # HTTP requests for ChatGPT API / Requisições HTTP para API do ChatGPT
  http: ^1.1.0
  # Screenshot capture / Captura de tela
  screenshot: ^3.0.0
  # Path utilities / Utilitários de caminho
  path_provider: ^2.1.1
  # JSON handling / Manipulação de JSON
  convert: ^3.1.1
  # System locale detection / Detecção de idioma do sistema
  devicelocale: ^0.8.1
  # Desktop integration / Integração com desktop
  desktop_window: ^0.4.0
  # State management
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/sprites/
    - assets/images/ui/
    - assets/sounds/
